-- Autogenerated ClickHouse schema based on cgds.sql
-- Generated on 2025-11-13T14:46:53.700247Z
DROP TABLE IF EXISTS `type_of_cancer`;
CREATE TABLE IF NOT EXISTS `type_of_cancer` (
  `TYPE_OF_CANCER_ID` String,
  `NAME` String,
  `DEDICATED_COLOR` String,
  `SHORT_NAME` Nullable(String),
  `PARENT` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`TYPE_OF_CANCER_ID`);

DROP TABLE IF EXISTS `reference_genome`;
CREATE TABLE IF NOT EXISTS `reference_genome` (
  `REFERENCE_GENOME_ID` Int32,
  `SPECIES` String,
  `NAME` String,
  `BUILD_NAME` String,
  `GENOME_SIZE` Nullable(Int64),
  `URL` String,
  `RELEASE_DATE` Nullable(DateTime) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`REFERENCE_GENOME_ID`);

DROP TABLE IF EXISTS `cancer_study`;
CREATE TABLE IF NOT EXISTS `cancer_study` (
  `CANCER_STUDY_ID` Int32,
  `CANCER_STUDY_IDENTIFIER` Nullable(String),
  `TYPE_OF_CANCER_ID` String,
  `NAME` String,
  `DESCRIPTION` String,
  `PUBLIC` String,
  `PMID` Nullable(String) DEFAULT NULL,
  `CITATION` Nullable(String) DEFAULT NULL,
  `GROUPS` Nullable(String) DEFAULT NULL,
  `STATUS` Nullable(Int32) DEFAULT NULL,
  `IMPORT_DATE` Nullable(DateTime) DEFAULT NULL,
  `REFERENCE_GENOME_ID` Nullable(Int32) DEFAULT 1
) ENGINE = MergeTree
ORDER BY (`CANCER_STUDY_ID`);

DROP TABLE IF EXISTS `cancer_study_tags`;
CREATE TABLE IF NOT EXISTS `cancer_study_tags` (
  `CANCER_STUDY_ID` Int32,
  `TAGS` String
) ENGINE = MergeTree
ORDER BY (`CANCER_STUDY_ID`);

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `EMAIL` String,
  `NAME` String,
  `ENABLED` String
) ENGINE = MergeTree
ORDER BY (`EMAIL`);

DROP TABLE IF EXISTS `authorities`;
CREATE TABLE IF NOT EXISTS `authorities` (
  `EMAIL` String,
  `AUTHORITY` String
) ENGINE = MergeTree
ORDER BY (`EMAIL`);

DROP TABLE IF EXISTS `patient`;
CREATE TABLE IF NOT EXISTS `patient` (
  `INTERNAL_ID` Int32,
  `STABLE_ID` String,
  `CANCER_STUDY_ID` Int32
) ENGINE = MergeTree
ORDER BY (`INTERNAL_ID`);

DROP TABLE IF EXISTS `sample`;
CREATE TABLE IF NOT EXISTS `sample` (
  `INTERNAL_ID` Int32,
  `STABLE_ID` String,
  `SAMPLE_TYPE` String,
  `PATIENT_ID` Int32
) ENGINE = MergeTree
ORDER BY (`INTERNAL_ID`);

DROP TABLE IF EXISTS `sample_list`;
CREATE TABLE IF NOT EXISTS `sample_list` (
  `LIST_ID` Int32,
  `STABLE_ID` String,
  `CATEGORY` String,
  `CANCER_STUDY_ID` Int32,
  `NAME` String,
  `DESCRIPTION` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`LIST_ID`);

DROP TABLE IF EXISTS `sample_list_list`;
CREATE TABLE IF NOT EXISTS `sample_list_list` (
  `LIST_ID` Int32,
  `SAMPLE_ID` Int32
) ENGINE = MergeTree
ORDER BY (`LIST_ID`, `SAMPLE_ID`);

DROP TABLE IF EXISTS `genetic_entity`;
CREATE TABLE IF NOT EXISTS `genetic_entity` (
  `ID` Int32,
  `ENTITY_TYPE` String,
  `STABLE_ID` Nullable(String) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`ID`);

DROP TABLE IF EXISTS `gene`;
CREATE TABLE IF NOT EXISTS `gene` (
  `ENTREZ_GENE_ID` Int32,
  `HUGO_GENE_SYMBOL` String,
  `GENETIC_ENTITY_ID` Int32,
  `TYPE` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`ENTREZ_GENE_ID`);

DROP TABLE IF EXISTS `gene_alias`;
CREATE TABLE IF NOT EXISTS `gene_alias` (
  `ENTREZ_GENE_ID` Int32,
  `GENE_ALIAS` String
) ENGINE = MergeTree
ORDER BY (`ENTREZ_GENE_ID`, `GENE_ALIAS`);

DROP TABLE IF EXISTS `geneset`;
CREATE TABLE IF NOT EXISTS `geneset` (
  `ID` Int32,
  `GENETIC_ENTITY_ID` String,
  `EXTERNAL_ID` String,
  `NAME` String,
  `DESCRIPTION` String,
  `REF_LINK` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`ID`);

DROP TABLE IF EXISTS `geneset_gene`;
CREATE TABLE IF NOT EXISTS `geneset_gene` (
  `GENESET_ID` Int32,
  `ENTREZ_GENE_ID` Int32
) ENGINE = MergeTree
ORDER BY (`GENESET_ID`, `ENTREZ_GENE_ID`);

DROP TABLE IF EXISTS `geneset_hierarchy_node`;
CREATE TABLE IF NOT EXISTS `geneset_hierarchy_node` (
  `NODE_ID` Int64,
  `NODE_NAME` String,
  `PARENT_ID` Nullable(String) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`NODE_ID`);

DROP TABLE IF EXISTS `geneset_hierarchy_leaf`;
CREATE TABLE IF NOT EXISTS `geneset_hierarchy_leaf` (
  `NODE_ID` Int32,
  `GENESET_ID` Int32
) ENGINE = MergeTree
ORDER BY (`NODE_ID`, `GENESET_ID`);

DROP TABLE IF EXISTS `generic_entity_properties`;
CREATE TABLE IF NOT EXISTS `generic_entity_properties` (
  `ID` Int32,
  `GENETIC_ENTITY_ID` Int32,
  `NAME` String,
  `VALUE` String
) ENGINE = MergeTree
ORDER BY (`ID`);

DROP TABLE IF EXISTS `genetic_profile`;
CREATE TABLE IF NOT EXISTS `genetic_profile` (
  `GENETIC_PROFILE_ID` Int32,
  `STABLE_ID` String,
  `CANCER_STUDY_ID` Int32,
  `GENETIC_ALTERATION_TYPE` String,
  `GENERIC_ASSAY_TYPE` Nullable(String) DEFAULT NULL,
  `DATATYPE` String,
  `NAME` String,
  `DESCRIPTION` Nullable(String),
  `SHOW_PROFILE_IN_ANALYSIS_TAB` Int32,
  `PIVOT_THRESHOLD` Nullable(Float32) DEFAULT NULL,
  `SORT_ORDER` Nullable(String) DEFAULT NULL,
  `PATIENT_LEVEL` Nullable(String) DEFAULT 0
) ENGINE = MergeTree
ORDER BY (`GENETIC_PROFILE_ID`);

DROP TABLE IF EXISTS `genetic_profile_link`;
CREATE TABLE IF NOT EXISTS `genetic_profile_link` (
  `REFERRING_GENETIC_PROFILE_ID` String,
  `REFERRED_GENETIC_PROFILE_ID` String,
  `REFERENCE_TYPE` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`REFERRING_GENETIC_PROFILE_ID`, `REFERRED_GENETIC_PROFILE_ID`);

DROP TABLE IF EXISTS `genetic_alteration`;
CREATE TABLE IF NOT EXISTS `genetic_alteration` (
  `GENETIC_PROFILE_ID` Int32,
  `GENETIC_ENTITY_ID` Int32,
  `VALUES` String
) ENGINE = MergeTree
ORDER BY (`GENETIC_PROFILE_ID`, `GENETIC_ENTITY_ID`);

DROP TABLE IF EXISTS `genetic_profile_samples`;
CREATE TABLE IF NOT EXISTS `genetic_profile_samples` (
  `GENETIC_PROFILE_ID` Int32,
  `ORDERED_SAMPLE_LIST` String
) ENGINE = MergeTree
ORDER BY (`GENETIC_PROFILE_ID`);

DROP TABLE IF EXISTS `gene_panel`;
CREATE TABLE IF NOT EXISTS `gene_panel` (
  `INTERNAL_ID` Int32,
  `STABLE_ID` String,
  `DESCRIPTION` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`INTERNAL_ID`);

DROP TABLE IF EXISTS `gene_panel_list`;
CREATE TABLE IF NOT EXISTS `gene_panel_list` (
  `INTERNAL_ID` Int32,
  `GENE_ID` Int32
) ENGINE = MergeTree
ORDER BY (`INTERNAL_ID`, `GENE_ID`);

DROP TABLE IF EXISTS `sample_profile`;
CREATE TABLE IF NOT EXISTS `sample_profile` (
  `SAMPLE_ID` Int32,
  `GENETIC_PROFILE_ID` Int32,
  `PANEL_ID` Nullable(Int32) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`SAMPLE_ID`);

DROP TABLE IF EXISTS `structural_variant`;
CREATE TABLE IF NOT EXISTS `structural_variant` (
  `INTERNAL_ID` Int32,
  `GENETIC_PROFILE_ID` Int32,
  `SAMPLE_ID` Int32,
  `SITE1_ENTREZ_GENE_ID` Nullable(Int32),
  `SITE1_ENSEMBL_TRANSCRIPT_ID` Nullable(String),
  `SITE1_CHROMOSOME` Nullable(String),
  `SITE1_REGION` Nullable(String),
  `SITE1_REGION_NUMBER` Nullable(Int32),
  `SITE1_CONTIG` Nullable(String),
  `SITE1_POSITION` Nullable(Int32),
  `SITE1_DESCRIPTION` Nullable(String),
  `SITE2_ENTREZ_GENE_ID` Nullable(Int32),
  `SITE2_ENSEMBL_TRANSCRIPT_ID` Nullable(String),
  `SITE2_CHROMOSOME` Nullable(String),
  `SITE2_REGION` Nullable(String),
  `SITE2_REGION_NUMBER` Nullable(Int32),
  `SITE2_CONTIG` Nullable(String),
  `SITE2_POSITION` Nullable(Int32),
  `SITE2_DESCRIPTION` Nullable(String),
  `SITE2_EFFECT_ON_FRAME` Nullable(String),
  `NCBI_BUILD` Nullable(String),
  `DNA_SUPPORT` Nullable(String),
  `RNA_SUPPORT` Nullable(String),
  `NORMAL_READ_COUNT` Nullable(Int32),
  `TUMOR_READ_COUNT` Nullable(Int32),
  `NORMAL_VARIANT_COUNT` Nullable(Int32),
  `TUMOR_VARIANT_COUNT` Nullable(Int32),
  `NORMAL_PAIRED_END_READ_COUNT` Nullable(Int32),
  `TUMOR_PAIRED_END_READ_COUNT` Nullable(Int32),
  `NORMAL_SPLIT_READ_COUNT` Nullable(Int32),
  `TUMOR_SPLIT_READ_COUNT` Nullable(Int32),
  `ANNOTATION` Nullable(String),
  `BREAKPOINT_TYPE` Nullable(String),
  `CONNECTION_TYPE` Nullable(String),
  `EVENT_INFO` Nullable(String),
  `CLASS` Nullable(String),
  `LENGTH` Nullable(Int32),
  `COMMENTS` Nullable(String),
  `SV_STATUS` String DEFAULT 'SOMATIC',
  `ANNOTATION_JSON` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`INTERNAL_ID`);

DROP TABLE IF EXISTS `alteration_driver_annotation`;
CREATE TABLE IF NOT EXISTS `alteration_driver_annotation` (
  `ALTERATION_EVENT_ID` Int32,
  `GENETIC_PROFILE_ID` Int32,
  `SAMPLE_ID` Int32,
  `DRIVER_FILTER` Nullable(String),
  `DRIVER_FILTER_ANNOTATION` Nullable(String),
  `DRIVER_TIERS_FILTER` Nullable(String),
  `DRIVER_TIERS_FILTER_ANNOTATION` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`ALTERATION_EVENT_ID`, `GENETIC_PROFILE_ID`, `SAMPLE_ID`);

DROP TABLE IF EXISTS `mutation_event`;
CREATE TABLE IF NOT EXISTS `mutation_event` (
  `MUTATION_EVENT_ID` Int32,
  `ENTREZ_GENE_ID` Int32,
  `CHR` Nullable(String),
  `START_POSITION` Nullable(Int64),
  `END_POSITION` Nullable(Int64),
  `REFERENCE_ALLELE` Nullable(String),
  `TUMOR_SEQ_ALLELE` Nullable(String),
  `PROTEIN_CHANGE` Nullable(String),
  `MUTATION_TYPE` Nullable(String),
  `NCBI_BUILD` Nullable(String),
  `STRAND` Nullable(String),
  `VARIANT_TYPE` Nullable(String),
  `DB_SNP_RS` Nullable(String),
  `DB_SNP_VAL_STATUS` Nullable(String),
  `REFSEQ_MRNA_ID` Nullable(String),
  `CODON_CHANGE` Nullable(String),
  `UNIPROT_ACCESSION` Nullable(String),
  `PROTEIN_POS_START` Nullable(Int32),
  `PROTEIN_POS_END` Nullable(Int32),
  `CANONICAL_TRANSCRIPT` Nullable(String),
  `KEYWORD` Nullable(String) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`MUTATION_EVENT_ID`);

DROP TABLE IF EXISTS `mutation`;
CREATE TABLE IF NOT EXISTS `mutation` (
  `MUTATION_EVENT_ID` Int32,
  `GENETIC_PROFILE_ID` Int32,
  `SAMPLE_ID` Int32,
  `ENTREZ_GENE_ID` Int32,
  `CENTER` Nullable(String),
  `SEQUENCER` Nullable(String),
  `MUTATION_STATUS` Nullable(String),
  `VALIDATION_STATUS` Nullable(String),
  `TUMOR_SEQ_ALLELE1` Nullable(String),
  `TUMOR_SEQ_ALLELE2` Nullable(String),
  `MATCHED_NORM_SAMPLE_BARCODE` Nullable(String),
  `MATCH_NORM_SEQ_ALLELE1` Nullable(String),
  `MATCH_NORM_SEQ_ALLELE2` Nullable(String),
  `TUMOR_VALIDATION_ALLELE1` Nullable(String),
  `TUMOR_VALIDATION_ALLELE2` Nullable(String),
  `MATCH_NORM_VALIDATION_ALLELE1` Nullable(String),
  `MATCH_NORM_VALIDATION_ALLELE2` Nullable(String),
  `VERIFICATION_STATUS` Nullable(String),
  `SEQUENCING_PHASE` Nullable(String),
  `SEQUENCE_SOURCE` String,
  `VALIDATION_METHOD` Nullable(String),
  `SCORE` Nullable(String),
  `BAM_FILE` Nullable(String),
  `TUMOR_ALT_COUNT` Nullable(Int32),
  `TUMOR_REF_COUNT` Nullable(Int32),
  `NORMAL_ALT_COUNT` Nullable(Int32),
  `NORMAL_REF_COUNT` Nullable(Int32),
  `AMINO_ACID_CHANGE` Nullable(String),
  `ANNOTATION_JSON` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`MUTATION_EVENT_ID`);

DROP TABLE IF EXISTS `mutation_count_by_keyword`;
CREATE TABLE IF NOT EXISTS `mutation_count_by_keyword` (
  `GENETIC_PROFILE_ID` Int32,
  `KEYWORD` Nullable(String) DEFAULT NULL,
  `ENTREZ_GENE_ID` Int32,
  `KEYWORD_COUNT` String,
  `GENE_COUNT` String
) ENGINE = MergeTree
ORDER BY (`GENETIC_PROFILE_ID`);

DROP TABLE IF EXISTS `clinical_patient`;
CREATE TABLE IF NOT EXISTS `clinical_patient` (
  `INTERNAL_ID` Int32,
  `ATTR_ID` String,
  `ATTR_VALUE` String
) ENGINE = MergeTree
ORDER BY (`INTERNAL_ID`, `ATTR_ID`);

DROP TABLE IF EXISTS `clinical_sample`;
CREATE TABLE IF NOT EXISTS `clinical_sample` (
  `INTERNAL_ID` Int32,
  `ATTR_ID` String,
  `ATTR_VALUE` String
) ENGINE = MergeTree
ORDER BY (`INTERNAL_ID`, `ATTR_ID`);

DROP TABLE IF EXISTS `clinical_attribute_meta`;
CREATE TABLE IF NOT EXISTS `clinical_attribute_meta` (
  `ATTR_ID` String,
  `DISPLAY_NAME` String,
  `DESCRIPTION` String,
  `DATATYPE` String,
  `PATIENT_ATTRIBUTE` String,
  `PRIORITY` String,
  `CANCER_STUDY_ID` Int32
) ENGINE = MergeTree
ORDER BY (`ATTR_ID`, `CANCER_STUDY_ID`);

DROP TABLE IF EXISTS `mut_sig`;
CREATE TABLE IF NOT EXISTS `mut_sig` (
  `CANCER_STUDY_ID` Int32,
  `ENTREZ_GENE_ID` Int32,
  `RANK` Int32,
  `NumBasesCovered` Int32,
  `NumMutations` Int32,
  `P_VALUE` Float32,
  `Q_VALUE` Float32
) ENGINE = MergeTree
ORDER BY (`CANCER_STUDY_ID`, `ENTREZ_GENE_ID`);

DROP TABLE IF EXISTS `gistic`;
CREATE TABLE IF NOT EXISTS `gistic` (
  `GISTIC_ROI_ID` Int64,
  `CANCER_STUDY_ID` Int32,
  `CHROMOSOME` Int32,
  `CYTOBAND` String,
  `WIDE_PEAK_START` Int32,
  `WIDE_PEAK_END` Int32,
  `Q_VALUE` Float64,
  `AMP` Int32
) ENGINE = MergeTree
ORDER BY (`GISTIC_ROI_ID`);

DROP TABLE IF EXISTS `gistic_to_gene`;
CREATE TABLE IF NOT EXISTS `gistic_to_gene` (
  `GISTIC_ROI_ID` Int64,
  `ENTREZ_GENE_ID` Int32
) ENGINE = MergeTree
ORDER BY (`GISTIC_ROI_ID`, `ENTREZ_GENE_ID`);

DROP TABLE IF EXISTS `cna_event`;
CREATE TABLE IF NOT EXISTS `cna_event` (
  `CNA_EVENT_ID` Int32,
  `ENTREZ_GENE_ID` Int32,
  `ALTERATION` String
) ENGINE = MergeTree
ORDER BY (`CNA_EVENT_ID`);

DROP TABLE IF EXISTS `sample_cna_event`;
CREATE TABLE IF NOT EXISTS `sample_cna_event` (
  `CNA_EVENT_ID` Int32,
  `SAMPLE_ID` Int32,
  `GENETIC_PROFILE_ID` Int32,
  `ANNOTATION_JSON` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`CNA_EVENT_ID`, `SAMPLE_ID`, `GENETIC_PROFILE_ID`);

DROP TABLE IF EXISTS `copy_number_seg`;
CREATE TABLE IF NOT EXISTS `copy_number_seg` (
  `SEG_ID` Int64,
  `CANCER_STUDY_ID` Int32,
  `SAMPLE_ID` Int32,
  `CHR` String,
  `START` Int32,
  `END` Int32,
  `NUM_PROBES` Int32,
  `SEGMENT_MEAN` Float64
) ENGINE = MergeTree
ORDER BY (`SEG_ID`);

DROP TABLE IF EXISTS `copy_number_seg_file`;
CREATE TABLE IF NOT EXISTS `copy_number_seg_file` (
  `SEG_FILE_ID` Int32,
  `CANCER_STUDY_ID` Int32,
  `REFERENCE_GENOME_ID` String,
  `DESCRIPTION` String,
  `FILENAME` String
) ENGINE = MergeTree
ORDER BY (`SEG_FILE_ID`);

DROP TABLE IF EXISTS `clinical_event`;
CREATE TABLE IF NOT EXISTS `clinical_event` (
  `CLINICAL_EVENT_ID` String,
  `PATIENT_ID` Int32,
  `START_DATE` String,
  `STOP_DATE` Nullable(String),
  `EVENT_TYPE` String
) ENGINE = MergeTree
ORDER BY (`CLINICAL_EVENT_ID`);

DROP TABLE IF EXISTS `clinical_event_data`;
CREATE TABLE IF NOT EXISTS `clinical_event_data` (
  `CLINICAL_EVENT_ID` String,
  `KEY` String,
  `VALUE` String
) ENGINE = MergeTree
ORDER BY (`CLINICAL_EVENT_ID`);

DROP TABLE IF EXISTS `reference_genome_gene`;
CREATE TABLE IF NOT EXISTS `reference_genome_gene` (
  `ENTREZ_GENE_ID` Int32,
  `REFERENCE_GENOME_ID` Int32,
  `CHR` Nullable(String) DEFAULT NULL,
  `CYTOBAND` Nullable(String) DEFAULT NULL,
  `START` Nullable(Int64) DEFAULT NULL,
  `END` Nullable(Int64) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`ENTREZ_GENE_ID`, `REFERENCE_GENOME_ID`);

DROP TABLE IF EXISTS `data_access_tokens`;
CREATE TABLE IF NOT EXISTS `data_access_tokens` (
  `TOKEN` String,
  `USERNAME` String,
  `EXPIRATION` DateTime,
  `CREATION` DateTime
) ENGINE = MergeTree
ORDER BY (`TOKEN`);

DROP TABLE IF EXISTS `allele_specific_copy_number`;
CREATE TABLE IF NOT EXISTS `allele_specific_copy_number` (
  `MUTATION_EVENT_ID` Int32,
  `GENETIC_PROFILE_ID` Int32,
  `SAMPLE_ID` Int32,
  `ASCN_INTEGER_COPY_NUMBER` Nullable(String) DEFAULT NULL,
  `ASCN_METHOD` String,
  `CCF_EXPECTED_COPIES_UPPER` Nullable(Float32) DEFAULT NULL,
  `CCF_EXPECTED_COPIES` Nullable(Float32) DEFAULT NULL,
  `CLONAL` Nullable(String) DEFAULT NULL,
  `MINOR_COPY_NUMBER` Nullable(String) DEFAULT NULL,
  `EXPECTED_ALT_COPIES` Nullable(String) DEFAULT NULL,
  `TOTAL_COPY_NUMBER` Nullable(String) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`MUTATION_EVENT_ID`);

DROP TABLE IF EXISTS `info`;
CREATE TABLE IF NOT EXISTS `info` (
  `DB_SCHEMA_VERSION` Nullable(String),
  `GENESET_VERSION` Nullable(String),
  `DERIVED_TABLE_SCHEMA_VERSION` Nullable(String),
  `GENE_TABLE_VERSION` Nullable(String)
) ENGINE = MergeTree
ORDER BY (tuple());

DROP TABLE IF EXISTS `resource_definition`;
CREATE TABLE IF NOT EXISTS `resource_definition` (
  `RESOURCE_ID` String,
  `DISPLAY_NAME` String,
  `DESCRIPTION` Nullable(String) DEFAULT NULL,
  `RESOURCE_TYPE` String,
  `OPEN_BY_DEFAULT` Nullable(String) DEFAULT 0,
  `PRIORITY` Int32,
  `CANCER_STUDY_ID` Int32,
  `CUSTOM_METADATA` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`RESOURCE_ID`, `CANCER_STUDY_ID`);

DROP TABLE IF EXISTS `resource_sample`;
CREATE TABLE IF NOT EXISTS `resource_sample` (
  `INTERNAL_ID` Int32,
  `RESOURCE_ID` String,
  `URL` String
) ENGINE = MergeTree
ORDER BY (`INTERNAL_ID`, `RESOURCE_ID`, `URL`);

DROP TABLE IF EXISTS `resource_patient`;
CREATE TABLE IF NOT EXISTS `resource_patient` (
  `INTERNAL_ID` Int32,
  `RESOURCE_ID` String,
  `URL` String
) ENGINE = MergeTree
ORDER BY (`INTERNAL_ID`, `RESOURCE_ID`, `URL`);

DROP TABLE IF EXISTS `resource_study`;
CREATE TABLE IF NOT EXISTS `resource_study` (
  `INTERNAL_ID` Int32,
  `RESOURCE_ID` String,
  `URL` String
) ENGINE = MergeTree
ORDER BY (`INTERNAL_ID`, `RESOURCE_ID`, `URL`);

DROP TABLE IF EXISTS `cosmic_mutation`;
CREATE TABLE IF NOT EXISTS `cosmic_mutation` (
  `COSMIC_MUTATION_ID` String,
  `CHR` String,
  `START_POSITION` Int64,
  `REFERENCE_ALLELE` String,
  `TUMOR_SEQ_ALLELE` String,
  `STRAND` String,
  `CODON_CHANGE` String,
  `ENTREZ_GENE_ID` Int32,
  `PROTEIN_CHANGE` String,
  `COUNT` Int32,
  `KEYWORD` String
) ENGINE = MergeTree
ORDER BY (`COSMIC_MUTATION_ID`);
