-- Autogenerated ClickHouse schema based on cgds.sql
-- Generated on 2025-11-14T09:48:58.877309Z
DROP TABLE IF EXISTS `cbioportal_sequence_state`;
CREATE TABLE IF NOT EXISTS `cbioportal_sequence_state` (
  `sequence_name` String,
  `last_value` UInt64
) ENGINE = ReplacingMergeTree
ORDER BY (`sequence_name`);

DROP TABLE IF EXISTS `type_of_cancer`;
CREATE TABLE IF NOT EXISTS `type_of_cancer` (
  `type_of_cancer_id` String,
  `name` String,
  `dedicated_color` String,
  `short_name` Nullable(String),
  `parent` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`type_of_cancer_id`);

DROP TABLE IF EXISTS `reference_genome`;
CREATE TABLE IF NOT EXISTS `reference_genome` (
  `reference_genome_id` Int32,
  `species` String,
  `name` String,
  `build_name` String,
  `genome_size` Nullable(Int64),
  `url` String,
  `release_date` Nullable(DateTime) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`reference_genome_id`);

DROP TABLE IF EXISTS `cancer_study`;
CREATE TABLE IF NOT EXISTS `cancer_study` (
  `cancer_study_id` Int32,
  `cancer_study_identifier` Nullable(String),
  `type_of_cancer_id` String,
  `name` String,
  `description` String,
  `public` String,
  `pmid` Nullable(String) DEFAULT NULL,
  `citation` Nullable(String) DEFAULT NULL,
  `groups` Nullable(String) DEFAULT NULL,
  `status` Nullable(Int32) DEFAULT NULL,
  `import_date` Nullable(DateTime) DEFAULT NULL,
  `reference_genome_id` Nullable(Int32) DEFAULT 1
) ENGINE = MergeTree
ORDER BY (`cancer_study_id`);

DROP TABLE IF EXISTS `cancer_study_tags`;
CREATE TABLE IF NOT EXISTS `cancer_study_tags` (
  `cancer_study_id` Int32,
  `tags` String
) ENGINE = MergeTree
ORDER BY (`cancer_study_id`);

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `email` String,
  `name` String,
  `enabled` String
) ENGINE = MergeTree
ORDER BY (`email`);

DROP TABLE IF EXISTS `authorities`;
CREATE TABLE IF NOT EXISTS `authorities` (
  `email` String,
  `authority` String
) ENGINE = MergeTree
ORDER BY (`email`);

DROP TABLE IF EXISTS `patient`;
CREATE TABLE IF NOT EXISTS `patient` (
  `internal_id` Int32,
  `stable_id` String,
  `cancer_study_id` Int32
) ENGINE = MergeTree
ORDER BY (`internal_id`);

DROP TABLE IF EXISTS `sample`;
CREATE TABLE IF NOT EXISTS `sample` (
  `internal_id` Int32,
  `stable_id` String,
  `sample_type` String,
  `patient_id` Int32
) ENGINE = MergeTree
ORDER BY (`internal_id`);

DROP TABLE IF EXISTS `sample_list`;
CREATE TABLE IF NOT EXISTS `sample_list` (
  `list_id` Int32,
  `stable_id` String,
  `category` String,
  `cancer_study_id` Int32,
  `name` String,
  `description` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`list_id`);

DROP TABLE IF EXISTS `sample_list_list`;
CREATE TABLE IF NOT EXISTS `sample_list_list` (
  `list_id` Int32,
  `sample_id` Int32
) ENGINE = MergeTree
ORDER BY (`list_id`, `sample_id`);

DROP TABLE IF EXISTS `genetic_entity`;
CREATE TABLE IF NOT EXISTS `genetic_entity` (
  `id` Int32,
  `entity_type` String,
  `stable_id` Nullable(String) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`id`);

DROP TABLE IF EXISTS `gene`;
CREATE TABLE IF NOT EXISTS `gene` (
  `entrez_gene_id` Int32,
  `hugo_gene_symbol` String,
  `genetic_entity_id` Int32,
  `type` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`entrez_gene_id`);

DROP TABLE IF EXISTS `gene_alias`;
CREATE TABLE IF NOT EXISTS `gene_alias` (
  `entrez_gene_id` Int32,
  `gene_alias` String
) ENGINE = MergeTree
ORDER BY (`entrez_gene_id`, `gene_alias`);

DROP TABLE IF EXISTS `geneset`;
CREATE TABLE IF NOT EXISTS `geneset` (
  `id` Int32,
  `genetic_entity_id` String,
  `external_id` String,
  `name` String,
  `description` String,
  `ref_link` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`id`);

DROP TABLE IF EXISTS `geneset_gene`;
CREATE TABLE IF NOT EXISTS `geneset_gene` (
  `geneset_id` Int32,
  `entrez_gene_id` Int32
) ENGINE = MergeTree
ORDER BY (`geneset_id`, `entrez_gene_id`);

DROP TABLE IF EXISTS `geneset_hierarchy_node`;
CREATE TABLE IF NOT EXISTS `geneset_hierarchy_node` (
  `node_id` Int64,
  `node_name` String,
  `parent_id` Nullable(String) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`node_id`);

DROP TABLE IF EXISTS `geneset_hierarchy_leaf`;
CREATE TABLE IF NOT EXISTS `geneset_hierarchy_leaf` (
  `node_id` String,
  `geneset_id` String
) ENGINE = MergeTree
ORDER BY (`node_id`, `geneset_id`);

DROP TABLE IF EXISTS `generic_entity_properties`;
CREATE TABLE IF NOT EXISTS `generic_entity_properties` (
  `id` Int32,
  `genetic_entity_id` String,
  `name` String,
  `value` String
) ENGINE = MergeTree
ORDER BY (`id`);

DROP TABLE IF EXISTS `genetic_profile`;
CREATE TABLE IF NOT EXISTS `genetic_profile` (
  `genetic_profile_id` Int32,
  `stable_id` String,
  `cancer_study_id` Int32,
  `genetic_alteration_type` String,
  `generic_assay_type` Nullable(String) DEFAULT NULL,
  `datatype` String,
  `name` String,
  `description` Nullable(String),
  `show_profile_in_analysis_tab` Int32,
  `pivot_threshold` Nullable(Float32) DEFAULT NULL,
  `sort_order` Nullable(String) DEFAULT NULL,
  `patient_level` Nullable(String) DEFAULT 0
) ENGINE = MergeTree
ORDER BY (`genetic_profile_id`);

DROP TABLE IF EXISTS `genetic_profile_link`;
CREATE TABLE IF NOT EXISTS `genetic_profile_link` (
  `referring_genetic_profile_id` String,
  `referred_genetic_profile_id` String,
  `reference_type` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`referring_genetic_profile_id`, `referred_genetic_profile_id`);

DROP TABLE IF EXISTS `genetic_alteration`;
CREATE TABLE IF NOT EXISTS `genetic_alteration` (
  `genetic_profile_id` Int32,
  `genetic_entity_id` Int32,
  `values` String
) ENGINE = MergeTree
ORDER BY (`genetic_profile_id`, `genetic_entity_id`);

DROP TABLE IF EXISTS `genetic_profile_samples`;
CREATE TABLE IF NOT EXISTS `genetic_profile_samples` (
  `genetic_profile_id` Int32,
  `ordered_sample_list` String
) ENGINE = MergeTree
ORDER BY (`genetic_profile_id`);

DROP TABLE IF EXISTS `gene_panel`;
CREATE TABLE IF NOT EXISTS `gene_panel` (
  `internal_id` Int32,
  `stable_id` String,
  `description` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`internal_id`);

DROP TABLE IF EXISTS `gene_panel_list`;
CREATE TABLE IF NOT EXISTS `gene_panel_list` (
  `internal_id` Int32,
  `gene_id` Int32
) ENGINE = MergeTree
ORDER BY (`internal_id`, `gene_id`);

DROP TABLE IF EXISTS `sample_profile`;
CREATE TABLE IF NOT EXISTS `sample_profile` (
  `sample_id` Int32,
  `genetic_profile_id` Int32,
  `panel_id` Nullable(Int32) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`sample_id`);

DROP TABLE IF EXISTS `structural_variant`;
CREATE TABLE IF NOT EXISTS `structural_variant` (
  `internal_id` Int32,
  `genetic_profile_id` Int32,
  `sample_id` Int32,
  `site1_entrez_gene_id` Nullable(Int32),
  `site1_ensembl_transcript_id` Nullable(String),
  `site1_chromosome` Nullable(String),
  `site1_region` Nullable(String),
  `site1_region_number` Nullable(Int32),
  `site1_contig` Nullable(String),
  `site1_position` Nullable(Int32),
  `site1_description` Nullable(String),
  `site2_entrez_gene_id` Nullable(Int32),
  `site2_ensembl_transcript_id` Nullable(String),
  `site2_chromosome` Nullable(String),
  `site2_region` Nullable(String),
  `site2_region_number` Nullable(Int32),
  `site2_contig` Nullable(String),
  `site2_position` Nullable(Int32),
  `site2_description` Nullable(String),
  `site2_effect_on_frame` Nullable(String),
  `ncbi_build` Nullable(String),
  `dna_support` Nullable(String),
  `rna_support` Nullable(String),
  `normal_read_count` Nullable(Int32),
  `tumor_read_count` Nullable(Int32),
  `normal_variant_count` Nullable(Int32),
  `tumor_variant_count` Nullable(Int32),
  `normal_paired_end_read_count` Nullable(Int32),
  `tumor_paired_end_read_count` Nullable(Int32),
  `normal_split_read_count` Nullable(Int32),
  `tumor_split_read_count` Nullable(Int32),
  `annotation` Nullable(String),
  `breakpoint_type` Nullable(String),
  `connection_type` Nullable(String),
  `event_info` Nullable(String),
  `class` Nullable(String),
  `length` Nullable(Int32),
  `comments` Nullable(String),
  `sv_status` String DEFAULT 'SOMATIC',
  `annotation_json` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`internal_id`);

DROP TABLE IF EXISTS `alteration_driver_annotation`;
CREATE TABLE IF NOT EXISTS `alteration_driver_annotation` (
  `alteration_event_id` Int32,
  `genetic_profile_id` Int32,
  `sample_id` Int32,
  `driver_filter` Nullable(String),
  `driver_filter_annotation` Nullable(String),
  `driver_tiers_filter` Nullable(String),
  `driver_tiers_filter_annotation` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`alteration_event_id`, `genetic_profile_id`, `sample_id`);

DROP TABLE IF EXISTS `mutation_event`;
CREATE TABLE IF NOT EXISTS `mutation_event` (
  `mutation_event_id` Int32,
  `entrez_gene_id` Int32,
  `chr` Nullable(String),
  `start_position` Nullable(Int64),
  `end_position` Nullable(Int64),
  `reference_allele` Nullable(String),
  `tumor_seq_allele` Nullable(String),
  `protein_change` Nullable(String),
  `mutation_type` Nullable(String),
  `ncbi_build` Nullable(String),
  `strand` Nullable(String),
  `variant_type` Nullable(String),
  `db_snp_rs` Nullable(String),
  `db_snp_val_status` Nullable(String),
  `refseq_mrna_id` Nullable(String),
  `codon_change` Nullable(String),
  `uniprot_accession` Nullable(String),
  `protein_pos_start` Nullable(Int32),
  `protein_pos_end` Nullable(Int32),
  `canonical_transcript` Nullable(String),
  `keyword` Nullable(String) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`mutation_event_id`);

DROP TABLE IF EXISTS `mutation`;
CREATE TABLE IF NOT EXISTS `mutation` (
  `mutation_event_id` Int32,
  `genetic_profile_id` Int32,
  `sample_id` Int32,
  `entrez_gene_id` Int32,
  `center` Nullable(String),
  `sequencer` Nullable(String),
  `mutation_status` Nullable(String),
  `validation_status` Nullable(String),
  `tumor_seq_allele1` Nullable(String),
  `tumor_seq_allele2` Nullable(String),
  `matched_norm_sample_barcode` Nullable(String),
  `match_norm_seq_allele1` Nullable(String),
  `match_norm_seq_allele2` Nullable(String),
  `tumor_validation_allele1` Nullable(String),
  `tumor_validation_allele2` Nullable(String),
  `match_norm_validation_allele1` Nullable(String),
  `match_norm_validation_allele2` Nullable(String),
  `verification_status` Nullable(String),
  `sequencing_phase` Nullable(String),
  `sequence_source` String,
  `validation_method` Nullable(String),
  `score` Nullable(String),
  `bam_file` Nullable(String),
  `tumor_alt_count` Nullable(Int32),
  `tumor_ref_count` Nullable(Int32),
  `normal_alt_count` Nullable(Int32),
  `normal_ref_count` Nullable(Int32),
  `amino_acid_change` Nullable(String),
  `annotation_json` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`mutation_event_id`);

DROP TABLE IF EXISTS `mutation_count_by_keyword`;
CREATE TABLE IF NOT EXISTS `mutation_count_by_keyword` (
  `genetic_profile_id` Int32,
  `keyword` Nullable(String) DEFAULT NULL,
  `entrez_gene_id` Int32,
  `keyword_count` String,
  `gene_count` String
) ENGINE = MergeTree
ORDER BY (`genetic_profile_id`);

DROP TABLE IF EXISTS `clinical_patient`;
CREATE TABLE IF NOT EXISTS `clinical_patient` (
  `internal_id` Int32,
  `attr_id` String,
  `attr_value` String
) ENGINE = MergeTree
ORDER BY (`internal_id`, `attr_id`);

DROP TABLE IF EXISTS `clinical_sample`;
CREATE TABLE IF NOT EXISTS `clinical_sample` (
  `internal_id` Int32,
  `attr_id` String,
  `attr_value` String
) ENGINE = MergeTree
ORDER BY (`internal_id`, `attr_id`);

DROP TABLE IF EXISTS `clinical_attribute_meta`;
CREATE TABLE IF NOT EXISTS `clinical_attribute_meta` (
  `attr_id` String,
  `display_name` String,
  `description` String,
  `datatype` String,
  `patient_attribute` String,
  `priority` String,
  `cancer_study_id` Int32
) ENGINE = MergeTree
ORDER BY (`attr_id`, `cancer_study_id`);

DROP TABLE IF EXISTS `mut_sig`;
CREATE TABLE IF NOT EXISTS `mut_sig` (
  `cancer_study_id` Int32,
  `entrez_gene_id` Int32,
  `rank` Int32,
  `numbasescovered` Int32,
  `nummutations` Int32,
  `p_value` Float32,
  `q_value` Float32
) ENGINE = MergeTree
ORDER BY (`cancer_study_id`, `entrez_gene_id`);

DROP TABLE IF EXISTS `gistic`;
CREATE TABLE IF NOT EXISTS `gistic` (
  `gistic_roi_id` Int64,
  `cancer_study_id` Int32,
  `chromosome` Int32,
  `cytoband` String,
  `wide_peak_start` Int32,
  `wide_peak_end` Int32,
  `q_value` Float64,
  `amp` Int32
) ENGINE = MergeTree
ORDER BY (`gistic_roi_id`);

DROP TABLE IF EXISTS `gistic_to_gene`;
CREATE TABLE IF NOT EXISTS `gistic_to_gene` (
  `gistic_roi_id` Int64,
  `entrez_gene_id` Int32
) ENGINE = MergeTree
ORDER BY (`gistic_roi_id`, `entrez_gene_id`);

DROP TABLE IF EXISTS `cna_event`;
CREATE TABLE IF NOT EXISTS `cna_event` (
  `cna_event_id` Int32,
  `entrez_gene_id` Int32,
  `alteration` String
) ENGINE = MergeTree
ORDER BY (`cna_event_id`);

DROP TABLE IF EXISTS `sample_cna_event`;
CREATE TABLE IF NOT EXISTS `sample_cna_event` (
  `cna_event_id` Int32,
  `sample_id` Int32,
  `genetic_profile_id` Int32,
  `annotation_json` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`cna_event_id`, `sample_id`, `genetic_profile_id`);

DROP TABLE IF EXISTS `copy_number_seg`;
CREATE TABLE IF NOT EXISTS `copy_number_seg` (
  `seg_id` Int64,
  `cancer_study_id` Int32,
  `sample_id` Int32,
  `chr` String,
  `start` Int32,
  `end` Int32,
  `num_probes` Int32,
  `segment_mean` Float64
) ENGINE = MergeTree
ORDER BY (`seg_id`);

DROP TABLE IF EXISTS `copy_number_seg_file`;
CREATE TABLE IF NOT EXISTS `copy_number_seg_file` (
  `seg_file_id` Int32,
  `cancer_study_id` Int32,
  `reference_genome_id` String,
  `description` String,
  `filename` String
) ENGINE = MergeTree
ORDER BY (`seg_file_id`);

DROP TABLE IF EXISTS `clinical_event`;
CREATE TABLE IF NOT EXISTS `clinical_event` (
  `clinical_event_id` String,
  `patient_id` Int32,
  `start_date` String,
  `stop_date` Nullable(String),
  `event_type` String
) ENGINE = MergeTree
ORDER BY (`clinical_event_id`);

DROP TABLE IF EXISTS `clinical_event_data`;
CREATE TABLE IF NOT EXISTS `clinical_event_data` (
  `clinical_event_id` String,
  `key` String,
  `value` String
) ENGINE = MergeTree
ORDER BY (`clinical_event_id`);

DROP TABLE IF EXISTS `reference_genome_gene`;
CREATE TABLE IF NOT EXISTS `reference_genome_gene` (
  `entrez_gene_id` Int32,
  `reference_genome_id` Int32,
  `chr` Nullable(String) DEFAULT NULL,
  `cytoband` Nullable(String) DEFAULT NULL,
  `start` Nullable(Int64) DEFAULT NULL,
  `end` Nullable(Int64) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`entrez_gene_id`, `reference_genome_id`);

DROP TABLE IF EXISTS `data_access_tokens`;
CREATE TABLE IF NOT EXISTS `data_access_tokens` (
  `token` String,
  `username` String,
  `expiration` DateTime,
  `creation` DateTime
) ENGINE = MergeTree
ORDER BY (`token`);

DROP TABLE IF EXISTS `allele_specific_copy_number`;
CREATE TABLE IF NOT EXISTS `allele_specific_copy_number` (
  `mutation_event_id` Int32,
  `genetic_profile_id` Int32,
  `sample_id` Int32,
  `ascn_integer_copy_number` Nullable(String) DEFAULT NULL,
  `ascn_method` String,
  `ccf_expected_copies_upper` Nullable(Float32) DEFAULT NULL,
  `ccf_expected_copies` Nullable(Float32) DEFAULT NULL,
  `clonal` Nullable(String) DEFAULT NULL,
  `minor_copy_number` Nullable(String) DEFAULT NULL,
  `expected_alt_copies` Nullable(String) DEFAULT NULL,
  `total_copy_number` Nullable(String) DEFAULT NULL
) ENGINE = MergeTree
ORDER BY (`mutation_event_id`);

DROP TABLE IF EXISTS `info`;
CREATE TABLE IF NOT EXISTS `info` (
  `db_schema_version` Nullable(String),
  `geneset_version` Nullable(String),
  `derived_table_schema_version` Nullable(String),
  `gene_table_version` Nullable(String)
) ENGINE = MergeTree
ORDER BY (tuple());

DROP TABLE IF EXISTS `resource_definition`;
CREATE TABLE IF NOT EXISTS `resource_definition` (
  `resource_id` String,
  `display_name` String,
  `description` Nullable(String) DEFAULT NULL,
  `resource_type` String,
  `open_by_default` Nullable(String) DEFAULT 0,
  `priority` Int32,
  `cancer_study_id` Int32,
  `custom_metadata` Nullable(String)
) ENGINE = MergeTree
ORDER BY (`resource_id`, `cancer_study_id`);

DROP TABLE IF EXISTS `resource_sample`;
CREATE TABLE IF NOT EXISTS `resource_sample` (
  `internal_id` Int32,
  `resource_id` String,
  `url` String
) ENGINE = MergeTree
ORDER BY (`internal_id`, `resource_id`, `url`);

DROP TABLE IF EXISTS `resource_patient`;
CREATE TABLE IF NOT EXISTS `resource_patient` (
  `internal_id` Int32,
  `resource_id` String,
  `url` String
) ENGINE = MergeTree
ORDER BY (`internal_id`, `resource_id`, `url`);

DROP TABLE IF EXISTS `resource_study`;
CREATE TABLE IF NOT EXISTS `resource_study` (
  `internal_id` Int32,
  `resource_id` String,
  `url` String
) ENGINE = MergeTree
ORDER BY (`internal_id`, `resource_id`, `url`);

DROP TABLE IF EXISTS `cosmic_mutation`;
CREATE TABLE IF NOT EXISTS `cosmic_mutation` (
  `cosmic_mutation_id` String,
  `chr` String,
  `start_position` Int64,
  `reference_allele` String,
  `tumor_seq_allele` String,
  `strand` String,
  `codon_change` String,
  `entrez_gene_id` Int32,
  `protein_change` String,
  `count` Int32,
  `keyword` String
) ENGINE = MergeTree
ORDER BY (`cosmic_mutation_id`);
