#!/usr/bin/env bash

DESTINATION_DATABASE="name_of_clickhouse_green_database"
read -p 'enter clickhouse password: ' password
echo "password was $password"

#TODO : read the table name list out of clickhouse and include any constructed views
table_name=()
table_name+=('allele_specific_copy_number')
table_name+=('alteration_driver_annotation')
table_name+=('authorities')
table_name+=('cancer_study')
table_name+=('cancer_study_tags')
table_name+=('clinical_attribute_meta')
table_name+=('clinical_event')
table_name+=('clinical_event_data')
table_name+=('clinical_patient')
table_name+=('clinical_sample')
table_name+=('cna_event')
table_name+=('copy_number_seg')
table_name+=('copy_number_seg_file')
table_name+=('cosmic_mutation')
table_name+=('data_access_tokens')
table_name+=('fraction_genome_altered')
table_name+=('gene')
table_name+=('gene_alias')
table_name+=('gene_panel')
table_name+=('gene_panel_list')
table_name+=('generic_entity_properties')
table_name+=('geneset')
table_name+=('geneset_gene')
table_name+=('geneset_hierarchy_leaf')
table_name+=('geneset_hierarchy_node')
table_name+=('genetic_alteration')
table_name+=('genetic_entity')
table_name+=('genetic_profile')
table_name+=('genetic_profile_link')
table_name+=('genetic_profile_samples')
table_name+=('gistic')
table_name+=('gistic_to_gene')
table_name+=('info')
table_name+=('mut_sig')
table_name+=('mutation')
table_name+=('mutation_count')
table_name+=('mutation_count_by_keyword')
table_name+=('mutation_event')
table_name+=('patient')
table_name+=('reference_genome')
table_name+=('reference_genome_gene')
table_name+=('resource_definition')
table_name+=('resource_patient')
table_name+=('resource_sample')
table_name+=('resource_study')
table_name+=('sample')
table_name+=('sample_cna_event')
table_name+=('sample_list')
table_name+=('sample_list_list')
table_name+=('sample_profile')
table_name+=('structural_variant')
table_name+=('type_of_cancer')
table_name+=('users')
table_name+=('sample_to_gene_panel_derived')
table_name+=('gene_panel_to_gene_derived')
table_name+=('sample_derived')
table_name+=('genomic_event_derived')
table_name+=('clinical_data_derived')
table_name+=('clinical_event_derived')
table_name+=('genetic_alteration_cna_derived')
table_name+=('genetic_alteration_numerical_derived')
table_name+=('generic_assay_data_derived')
table_name+=('sample_list_columnstore')
#TODO a separate command is needed for dropping views, so make sure to keep the table list and the view list distinct (read both out of the clickhouse service)
#view_name+=('sample_list_columnstore_mv")
pos=0
while [ $pos -lt 63 ] ; do
    clickhouse client --host clickhouse_hostname_goes_here --port clickhouse_port_goes_here --user username_goes_here --password="$password" <<< "DROP TABLE $DESTINATION_DATABASE.${table_name[$pos]}" 
    pos=$(($pos+1))
done
while [ $pos -lt 1 ] ; do
    clickhouse client --host clickhouse_hostname_goes_here --port clickhouse_port_goes_here --user username_goes_here --password="$password" <<< "DROP MATERIALIZED VIEW $DESTINATION_DATABASE.${view_name[$pos]}" 
    pos=$(($pos+1))
done
