name: Docker Image CI
on:
  push:
    branches:
      - main
      - 'demo*'
    tags: '*'

jobs:
  build_and_publish_image:
    if: github.repository == 'cBioPortal/cbioportal-core'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            cbioportal/cbioportal-core
          # Do not generate latest tag
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # The following two actions are required to build multi-platform images
      # buildx is an extension of docker build, QUEM is used to convert the binary to varies architecture
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish Docker Image on Tag
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha
